### ISSUE TITLE
X-Errors when configuring

### ISSUE THREAD

**Issue by Merovius** [Merovius/shellex#17]
On some systems, there is an X-Error when initiallly configuring the window. The problem is this [magic constant](https://github.com/Merovius/shellex/blob/master/urxvt/shellex.in#L201), it appears, you have to add some pixels, for some reasons, to the fontheight. 2 works on my system, but not on others, so it seems to be dependent on the font or something. It's a minor nuisance, but we should figure out, why we need that and how to get it at runtime.

**Comment by pseyfert** [comment]
The modification of `on_start` resolves the X-Errors. The part in `resize_rows` incorrectly always resizes to one row for me.
