### ISSUE TITLE
It would be nice there are some screenshots of what this is

### ISSUE THREAD

**Issue by blurmonk** [Merovius/shellex#29]
Hi

I was browsing launchers and saw this but the thing is that nos creenshot is provided which makes it hard to judge what it is all about.

thanks

**Comment by pseyfert** [comment]
find a demo here:
http://virgilio.mib.infn.it/~seyfert/videos/shellexdemo.webm
![demo](http://virgilio.mib.infn.it/~seyfert/images/shellexdemo.gif)

**Comment by Merovius** [comment]
Closed with 81c35d3a92c4926064afe32cff33be678a8c72de
