### ISSUE TITLE
Shellex bar doesn't open

### ISSUE THREAD

**Issue by benoncoffee** [Merovius/shellex#64]
I did a fresh install of Arch Linux with i3gaps. I installed shellex via the Arch User Repository (AUR), and configured i3 to bind alt+d to shellex.

When I press alt+d, a dark bar is visible at the top of my screen for about 0.1 second. Running shellex from the terminal gives the following output:
```
ruben@T410 » shellex                                                                                             ~
position should be at the top
Getting shellex-position from focused window
size_change(1440, 15)
urxvt: An X Error occurred, trying to continue after report.
urxvt: + Serial number of failed request:  147
urxvt: + X Error of failed request: BadValue (integer parameter out of range for operation)
urxvt: + Major opcode of failed request:  12
urxvt: + (which is X_ConfigureWindow)
urxvt: + Value in failed request:  0x0
line_update(row = 0)
resizing to 1
size_change(1440, 17)
line_update(row = 1)
resizing to 1
line_update(row = 2)
resizing to 1
line_update(row = 3)
resizing to 1
```
(the line_update(row=..) and resizing continues until row = 23).

For me, commenting out the first line of the shellex script in /usr/bin/shellex, fixes the issue (that is, I put changed the line 
`LD_PRELOAD="/usr/lib/shellex/shellex_preload.so"`
to
`# LD_PRELOAD="/usr/lib/shellex/shellex_preload.so"`

So I do have a workaround for this issue (although I haven't tested it thoroughly). I am reporting this issue just for the record. I can't change the status of this issue myself, so it's "open" for now. I figured that LD_PRELOAD might be doing something important, so it's possible that I will run into other issues as a result later.

**Comment by pseyfert** [comment]
Thanks for reporting, I think the AUR version uses the latest tag (I should tag a new version) do you mind trying with the master version from github?

In layperson's terms, the preload library steers the resizing behaviour, so this gets relevant when you tab complete something with many suggestions and we need to ensure shellex doesn't grow larger than the screen and the shell knows how much space it has and when to start scrolling through completions.
I'm not sure what to expect when the preload is missing completely but starting applications should work just fine.

**Comment by benoncoffee** [comment]
The github version works! Sorry for that, I probably should have checked it first.

**Comment by pseyfert** [comment]
Don't worry and thanks for bringing that up. I'll keep it open as "get a new tag into AUR".

**Comment by pseyfert** [comment]
0.3 is now in AUR. (it's entirely on me that it took so long)
